allowBuilds:
  '@tailwindcss/oxide': true
  core-js: true
  esbuild: true
  sharp: true
  spawn-sync: true
  vue-demi: true
onlyBuiltDependencies:
  - canvas
  - core-js
  - esbuild
  - sharp
  - spawn-sync
  - vue-demi
